id: mongo
name: MongoDB
description: The MongoDB Database.
color: '#47A248'
icon: simpleicons/mongo.svg

methods:
  docker:
    image: mongo
    volumes:
      db: /data/db
    ports:
      27017: 27017
