id: code-server
name: Code Server
description: VSCode in the browser
color: '#007ACC'
icon: code-server.svg

environment:
  - type: port
    name: PORT
    display_name: Port
    default: 8080
    description: The port to expose Code Server.

urls:
  - name: Code Server
    port: 8080
    kind: client

methods:
  docker:
    image: linuxserver/code-server
    ports:
      8443: 8080
    volumes:
      config: /config

  script:
    file: start.sh
    dependencies:
      code-server:
